version: '3.8'

services:
  backend:
    image: 775727899931.dkr.ecr.ap-south-1.amazonaws.com/djjs-backend:latest
    container_name: djjs-backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - djjs-net
    env_file:
      - .env

networks:
  djjs-net:
    external: true
